global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s 
    metrics_path: /monitoring
    static_configs:
      # TODO: Replace with actual Railway deployment URL after deployment.
      # Example: 'my-app.up.railway.app:8501'
      - targets: ['mlops-deploy.up.railway.app:443']