global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "tf-serving-monitor"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tensorflow-serving-railway'
    metrics_path: '/monitoring'  # <-- Path yang benar untuk TF Serving
    scheme: 'https'  # <-- WAJIB: Railway menggunakan HTTPS
    scrape_interval: 5s
    static_configs:
      - targets: ['mlops-deploy.up.railway.app']  # <-- Tanpa port (HTTPS default 443)